# Generated by Django 6.0.2 on 2026-02-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_periodic_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
