# Generated by Django 6.0.2 on 2026-02-05 21:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_periodic_tasks', '0002_remove_redundant_next_run_at_db_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='django_periodic_tasks.scheduledtask')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status', 'pending')), fields=['status'], name='periodic_pending_exec_idx')],
            },
        ),
    ]
